In [1]:
import pandas as pd
import os
import numpy as np
import csv
import re

In [2]:
csv_path = r'G:\Deep_Learning\kaggle\global-wheat-detection\dataset\train.csv'
# train_dir = r'G:\Deep_Learning\kaggle\global-wheat-detection\dataset\train'

In [3]:
df = pd.read_csv(csv_path)
df.head()

image_id  width  height                         bbox   source
0  b6ab77fd7   1024    1024   [834.0, 222.0, 56.0, 36.0]  usask_1
1  b6ab77fd7   1024    1024  [226.0, 548.0, 130.0, 58.0]  usask_1
2  b6ab77fd7   1024    1024  [377.0, 504.0, 74.0, 160.0]  usask_1
3  b6ab77fd7   1024    1024  [834.0, 95.0, 109.0, 107.0]  usask_1
4  b6ab77fd7   1024    1024  [26.0, 144.0, 124.0, 117.0]  usask_1

In [4]:
def process_bbox(df):
    ids = []
    values = []
    imd = np.unique(df['image_id'])
    df['bbox'] = df['bbox'].apply(lambda x: eval(x))
    # for image_id in os.listdir(train_dir):
    #     image_id = image_id.split('.')[0]
    #     if image_id not in imd :
    #         ids.append(image_id)
    #         values.append(str([-1,-1,-1,-1]))
    # new_df = {'image_id':ids, 'bbox':values}
    # new_df = pd.DataFrame(new_df)
    df = df[['image_id','bbox']]
    # df.append(new_df)
    df = df.reset_index(drop=True)
    df['x'] = df['bbox'].apply(lambda x: x[0])
    df['y'] = df['bbox'].apply(lambda x: x[1])
    df['w'] = df['bbox'].apply(lambda x: x[2])
    df['h'] = df['bbox'].apply(lambda x: x[3])

    df.drop(columns=['bbox'],inplace=True)
    return df

In [5]:
df_ = process_bbox(df)

df_.head()

image_id      x      y      w      h
0  b6ab77fd7  834.0  222.0   56.0   36.0
1  b6ab77fd7  226.0  548.0  130.0   58.0
2  b6ab77fd7  377.0  504.0   74.0  160.0
3  b6ab77fd7  834.0   95.0  109.0  107.0
4  b6ab77fd7   26.0  144.0  124.0  117.0

In [6]:
names = df_.loc[:,'image_id'].unique()
print(names)
len(names)

['b6ab77fd7' 'b53afdf5c' '7b72ea0fb' ... 'a5c8d5f5c' 'e6b5e296d'
 '5e0747034']


3373

In [7]:
df_idx = df_.set_index("image_id")
df_idx.head()

x      y      w      h
image_id                             
b6ab77fd7  834.0  222.0   56.0   36.0
b6ab77fd7  226.0  548.0  130.0   58.0
b6ab77fd7  377.0  504.0   74.0  160.0
b6ab77fd7  834.0   95.0  109.0  107.0
b6ab77fd7   26.0  144.0  124.0  117.0

In [8]:
# a = df_idx.loc['f0508910d'].head()

In [9]:
# a1 = a.reset_index(drop=True)
# a2 = a1.to_numpy()
# print(a2)
# for row in a2:
#     print('\n')
#     print(row)

[[  0. 850.  55. 100.]
 [301. 943.  76.  81.]
 [642. 932.  61.  92.]
 [362. 770. 101. 157.]
 [569. 784. 116. 100.]]


In [10]:
scale = 1024
i = 0
q = 0
for name in names:
    # print(name, '\n')
    txtName = str(name) + '.txt'
    # print(txtName)
    f=open('G:\Deep_Learning\kaggle\global-wheat-detection\demo\labels/' + txtName, "a+")
    a = df_idx.loc[str(name)]
    a = a.reset_index(drop=True)
    a = a.to_numpy()
    # print(len(a))
    for row in a:
        try:
            x = row[0]
            y = row[1]
            w = row[2]
            h = row[3]
        except IndexError:
            q = q + 1
            print(name)
            continue
        x_c = (x + w/2) / scale
        y_c = (y + h/2) / scale
        w = w / scale
        h = h / scale
        # print(x, y, w, h )
        f.write(str(0)+' '+str(x_c)+' '+str(y_c)+' '+str(w)+' '+str(h)+'\n')
    f.close()
    i = i + 1
print("共",i,"次")
print(q,"次错误")

共 10 次
0 次错误
