In [1]:
import pandas as pd
import os
import numpy as np
import csv
import re

In [2]:
csv_path = r'G:\Deep_Learning\kaggle\global-wheat-detection\dataset\train.csv'

In [5]:
df = pd.read_csv(csv_path)
df.head()

image_id  width  height                         bbox   source
0  b6ab77fd7   1024    1024   [834.0, 222.0, 56.0, 36.0]  usask_1
1  b6ab77fd7   1024    1024  [226.0, 548.0, 130.0, 58.0]  usask_1
2  b6ab77fd7   1024    1024  [377.0, 504.0, 74.0, 160.0]  usask_1
3  b6ab77fd7   1024    1024  [834.0, 95.0, 109.0, 107.0]  usask_1
4  b6ab77fd7   1024    1024  [26.0, 144.0, 124.0, 117.0]  usask_1

In [6]:
def process_bbox(df):
    ids = []
    values = []
    imd = np.unique(df['image_id'])
    df['bbox'] = df['bbox'].apply(lambda x: eval(x))
    # for image_id in os.listdir(train_dir):
    #     image_id = image_id.split('.')[0]
    #     if image_id not in imd :
    #         ids.append(image_id)
    #         values.append(str([-1,-1,-1,-1]))
    # new_df = {'image_id':ids, 'bbox':values}
    # new_df = pd.DataFrame(new_df)
    df = df[['image_id','bbox']]
    # df.append(new_df)
    df = df.reset_index(drop=True)
    df['x'] = df['bbox'].apply(lambda x: x[0])
    df['y'] = df['bbox'].apply(lambda x: x[1])
    df['w'] = df['bbox'].apply(lambda x: x[2])
    df['h'] = df['bbox'].apply(lambda x: x[3])

    df.drop(columns=['bbox'],inplace=True)
    return df

In [7]:
df_ = process_bbox(df)

df_.head()

image_id      x      y      w      h
0  b6ab77fd7  834.0  222.0   56.0   36.0
1  b6ab77fd7  226.0  548.0  130.0   58.0
2  b6ab77fd7  377.0  504.0   74.0  160.0
3  b6ab77fd7  834.0   95.0  109.0  107.0
4  b6ab77fd7   26.0  144.0  124.0  117.0

In [23]:
df_idx = df_.set_index("image_id")
bbox = df_idx.reset_index(drop=True)
bbox.head()

x      y      w      h
0  834.0  222.0   56.0   36.0
1  226.0  548.0  130.0   58.0
2  377.0  504.0   74.0  160.0
3  834.0   95.0  109.0  107.0
4   26.0  144.0  124.0  117.0

In [37]:
bbox_arr = bbox.to_numpy()
w_h = bbox_arr[:,(2,3)]
w_h

array([[ 56.,  36.],
       [130.,  58.],
       [ 74., 160.],
       ...,
       [141.,  71.],
       [184.,  79.],
       [ 94.,  61.]])

In [38]:
anchors = []
for b in w_h[:5]:
    anchors.append(b)
anchors

[array([56., 36.]),
 array([130.,  58.]),
 array([ 74., 160.]),
 array([109., 107.]),
 array([124., 117.])]